### ISSUE TITLE
Registering displayers for interfaces doesn't work

### ISSUE THREAD

**Issue by jpallas** [jupyter/jvm-repr#8]
The implementation of `Registration.find()` walks the superclass chain looking for a matching displayer.  This means that registering a displayer for an interface has no effect (the registration will succeed, but the displayer will never be found).

There would need to be some way to resolve the ambiguity if matches were found for both a class and an interface or for two interfaces.

**Comment by scottdraves** [comment]
See https://github.com/twosigma/beakerx/pull/5920

**Comment by rdblue** [comment]
Was there a resolution on this? Did you find a good way to do it? I'm happy to review a patch, but I'm not sure what we should do here. Maybe just detect an interface and not allow it for now?

**Comment by jpallas** [comment]
I was hoping someone might weigh in with an opinion about how best to deal with ambiguous cases.  My thoughts: Interfaces and classes are kept separate.  If there's a matching interface that is a lower bound on all the matching interfaces, that's clearly the best matching interface.  If there's a matching class and matching interfaces, I _think_ class should take priority, as it's logically more specific.  That leaves what to do if the set of matching interfaces doesn't have a lower bound.  The easy way out would be to say one will be chosen by unspecified means.

A naive implementation would scale badly with the number of interfaces.  But since interfaces aren't supported at all currently, that might be okay for a first cut.

**Comment by rdblue** [comment]
Okay, I implemented a patch that traverses interfaces after checking a class. This now uses the closest interface or class to the object. If the object's class has an interface, it will be used before the superclass, the superclass will be used before the superclass' interfaces, and so on.

**Comment by rdblue** [comment]
> . . . what to do if the set of matching interfaces doesn't have a lower bound . . .

The patch in #11 traverses interfaces in the order they are declared on a class, from left to right.

**Comment by jpallas** [comment]
(Echoing what I said in a comment on #11) I think a solution must allow for an interface that is not directly implemented by any of the classes in the superclass chain.  That is, if interface B extends interface A and class C implements interface B, looking up a displayer for class C must find one registered for interface A if there's no other match.

Unfortunately, `getInterfaces()` reflects only the declaration of a class/interface, not the full hierarchy.

**Comment by rdblue** [comment]
Merged #11 and released 0.3.0 with the update. Thanks @jpallas!
